[package]
name = "planetary-logic"
version = "0.1.0"
authors = ["Alexey Erzyamkin <aerzyamkin@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
specs = { version = "0.15", features = ["specs-derive"] }