version: '3.5'
services:
  
  mongo:
    image: mongo:4.0-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: backend
    ports:
      - "27017:27017"
    networks: 
      - backend
  
networks:
  backend:
    name: "backend"